fakerdefaults:
  storeType: mysql
  batchSize: 100
  lineEvadeInterval: 10.0
  localesInfo:
    defaultLocale: en
    separateBelow: 2
    supportedLocales:
      - en
      - zh-CN
      - bg
      - ca
      - ca-CAT
      - da-DK
      - de
      - de-AT
      - de-CH
      - en-AU
      - en-au-ocker
      - en-BORK
      - en-CA
      - en-GB
      - en-IND
      - en-MS
      - en-NEP
      - en-NG
      - en-NZ
      - en-PAK
      - en-SG
      - en-UG
      - en-US
      - en-ZA
      - es
      - es-MX
      - fa
      - fi-FI
      - fr
      - he
      - hu
      - in-ID
      - it
      - ja
      - ko
      - nb-NO
      - nl
      - pl
      - pt
      - pt-BR
      - ru
      - sk
      - sv
      - sv-SE
      - tr
      - uk
      - vi
      - zh-TW